{{- if .Values.persistentVolume.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.environment }}
    type: local
spec:
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  volumeMode: Filesystem

  {{- if .Values.persistentVolume.nodeAffinity }}
  nodeAffinity:
    {{- toYaml .Values.persistentVolume.nodeAffinity | nindent 4 }}
  {{- end }}

  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
    type: DirectoryOrCreate
{{- end }}
