apiVersion: v2
name: linktree-backend
description: Linktree Backend API with Argo Rollouts (BlueGreen/Canary) and CloudNativePG
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - linktree
  - nodejs
  - backend
  - argo-rollouts
  - postgresql
maintainers:
  - name: periclesanfe

dependencies:
  - name: postgresql
    version: "1.0.0"
    condition: postgresql.enabled
