apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linktree.fullname" . }}-backend-config
  labels:
    {{- include "linktree.backend.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.service.port | quote }}
  NODE_ENV: {{ .Values.environment | quote }}
  CORS_ORIGIN: {{ .Values.backend.corsOrigin | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.database | quote }}
