apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linktree.fullname" . }}-frontend-config
  labels:
    {{- include "linktree.frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.frontend.apiUrl | quote }}
