apiVersion: v2
name: linktree
description: Linktree application (Backend API + Frontend SPA)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - linktree
  - nodejs
  - react
  - full-stack
maintainers:
  - name: periclesanfe

# Dependencies (subcharts)
dependencies:
  - name: backend
    version: "1.0.0"
    repository: "file://./charts/backend"
    condition: backend.enabled
  - name: frontend
    version: "1.0.0"
    repository: "file://./charts/frontend"
    condition: frontend.enabled
