# Garante disponivilidade dos pods do backend durante interrupções planejadas

{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "linktree.backend.fullname" . }}
  labels:
    {{- include "linktree.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "linktree.backend.selectorLabels" . | nindent 6 }}
{{- end }}
