{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linktree.backend.fullname" . }}-config
  labels:
    {{- include "linktree.backend.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.config.port | quote }}
  NODE_ENV: {{ .Values.backend.config.nodeEnv | quote }}
  CORS_ORIGIN: {{ .Values.backend.config.corsOrigin | quote }}
  DB_HOST: {{ .Values.backend.database.host | quote }}
  DB_PORT: {{ .Values.backend.database.port | quote }}
  DB_NAME: {{ .Values.backend.database.database | quote }}
{{- end }}
