{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linktree.frontend.fullname" . }}-config
  labels:
    {{- include "linktree.frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.frontend.config.apiUrl | quote }}
{{- end }}
