{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "linktree.frontend.fullname" . }}
  labels:
    {{- include "linktree.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "linktree.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
