{{- if eq .Values.environment "dev" }}
# Service preview para BlueGreen (somente DEV)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linktree.fullname" . }}-preview
  labels:
    {{- include "linktree.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "linktree.selectorLabels" . | nindent 4 }}
{{- end }}
