apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.environment }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}
